# Generated by Django 3.1.14 on 2022-04-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220404_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='deploy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='deploy'),
        ),
    ]
